# Generated by Django 4.2.5 on 2023-11-08 00:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userlocation", "0004_fishingmarks"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Fishingmarks",
            new_name="Fishingmark",
        ),
    ]
